set -g default-shell /bin/zsh

set-option -g mouse on
setw -g mode-keys vi
set-option -g base-index 1

# binds

unbind f12
set-option -g prefix2 f12
bind-key , command-prompt "rename-window '%%'"
bind -n C-k clear-history
bind -n C-f command-prompt -p "(search)" "split-window 'exec tmux search -w \"%%%\"'"

# plugins

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'
set -g @continuum-boot-options 'iterm'

set -g @plugin 'nhdaly/tmux-better-mouse-mode'
setw -g mouse on


set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @theme_variation 'night'

set-option -g @plugin 'b0o/tmux-autoreload'

run '~/.tmux/plugins/tpm/tpm'
